services:
  server:
    build: .
    volumes:
      - ./data:/minecraft
    environment:
      EULA: "true"
    ports:
      - "25565:25565"
    entrypoint: ["/bin/sh", "-c", "echo 'eula=true' > eula.txt && java -jar server.jar nogui"]
